Rifex 261/clear search bar
anarancio/nifty-wallet pull request #141
Opened 2020-07-21 18:06 UTC by TheLagger69

Clear search bar when searching for a domain
- Search bar is cleared after searching for a domain that doesn't exist.
-  Search bar is not shown in domain detail page.

Note: A minor refactor was done in genericSearch, in order to handle the search text as a state property, and clear it when needed.

2020-07-21 20:19 UTC, rorolopetegui requested changes
LGTM Just delete the error log that i think it will be always showed

2020-07-21 20:19 UTC, rorolopetegui commented on ui/app/rif/components/genericSearch/index.js
> +    console.error('limpio');
Please delete this log, or we can have an error here?

2020-07-21 20:54 UTC, JONAF2103 requested changes
In general it looks good but please make those constant functions into the standar functions that we are using, instead of having somefunction = () => {} we are using the class member approach like this somefunction () {} inside the component class. With that you don't have to use bind in the constructor.

2020-07-21 21:01 UTC, TheLagger69 commented
> In general it looks good but please make those constant functions into the standar functions that we are using, instead of having somefunction = () => {} we are using the class member approach like this somefunction () {} inside the component class. With that you don't have to use bind in the constructor.

Ok, I'll change it. Anyway, I'm almost sure binding will still be needed

2020-07-22 14:31 UTC, rorolopetegui approved these changes
lgtm

2020-07-22 18:28 UTC, JONAF2103 approved these changes
LGTM

2020-07-23 13:04 UTC, merged