RIFEX-293/EditAdd-chainaddress-same-value
anarancio/nifty-wallet pull request #159
Opened 2020-07-24 22:13 UTC by rorolopetegui

This PR fixes that when you try to add a chain address that's already added, it shows a toast message that it cant add it
Also fixes that when you try to update a chain address with the same value that it has

![ChainAddressalreadyaddedResized](https://user-images.githubusercontent.com/35036353/88439485-c1253c00-cde1-11ea-91ce-fe66ade2d22b.gif)

2020-07-24 22:46 UTC, mauricioirace reviewed
LGTM.

(I'm almost sure past participle of 'set' is 'set', but I see nothing really important preventing this to being merged from my perspective)

2020-07-27 02:17 UTC, marcosmartinez7 requested changes
lgtm in general, just improve the error msgs

2020-07-27 02:17 UTC, marcosmartinez7 commented on ui/app/rif/components/chainAddresses.js
> +      this.props.showToast('Can\'t try to update an address that\'s already setted', false);
Improve this message, its incorrect syntactically speaking.

My suggestion: "The address already has the same value"

2020-07-27 02:17 UTC, marcosmartinez7 commented on ui/app/rif/components/chainAddresses.js
> +      this.props.showToast('Can\'t add an address that\'s already setted. Try updating it from the list', false);
"Address is already present. Try updating it from the list or add a new one" seems better to me

2020-07-27 14:10 UTC, marcosmartinez7 approved these changes

2020-07-29 12:14 UTC, merged